SET(TW_GAME_SRC_TOY_WORLD_APP
	"ToyWorldApp/ToyWorldApplication.cpp"
	""
)

SET(TW_GAME_INC_TOY_WORLD_APP
	"ToyWorldApp/ToyWorldApplication.h"
)


# if(MSVC)
# 	list(APPEND BS_BANSHEECORE_INC_PLATFORM VSVisualizations.natvis)
# endif()

# if(WIN32)
# 	list(APPEND BS_BANSHEECORE_INC_PLATFORM ${BS_BANSHEECORE_INC_PLATFORM_WIN32})
# 	list(APPEND BS_BANSHEECORE_SRC_PLATFORM ${BS_BANSHEECORE_SRC_PLATFORM_WIN32})
# elseif(LINUX)
# 	list(APPEND BS_BANSHEECORE_INC_PLATFORM ${BS_BANSHEECORE_INC_PLATFORM_LINUX})
# 	list(APPEND BS_BANSHEECORE_SRC_PLATFORM ${BS_BANSHEECORE_SRC_PLATFORM_LINUX})
# elseif(APPLE)
# 	list(APPEND BS_BANSHEECORE_INC_PLATFORM ${BS_BANSHEECORE_INC_PLATFORM_MACOS})
# 	list(APPEND BS_BANSHEECORE_SRC_PLATFORM ${BS_BANSHEECORE_SRC_PLATFORM_MACOS})
# endif()

source_group("Header Files\\ToyWorldApp" 				FILES ${TW_GAME_INC_TOY_WORLD_APP})
source_group("Source Files\\ToyWorldApp" 				FILES ${TW_GAME_SRC_TOY_WORLD_APP})
source_group("CMake" 									FILES "CMakeSources.cmake" "CMakeLists.txt")


set(TW_GAME_SRC
	"CMakeSources.cmake" "CMakeLists.txt"
	${TW_GAME_INC_TOY_WORLD_APP}
	${TW_GAME_SRC_TOY_WORLD_APP}
)
